---
- name: Install MariaDB Server
  apt:
    name: mariadb-server
    state: present
    update_cache: yes
  become: yes

- name: Ensure MariaDB is running
  service:
    name: mariadb
    state: started
    enabled: yes
  become: yes

- name: Install Python MySQL client library
  apt:
    name: python3-mysqldb
    state: present
  become: yes

- name: Check if root password is already set
  command: >
    mysql --login-unix-socket=/var/run/mysqld/mysqld.sock -u root -e "SELECT 1;"
  register: mysql_root_access
  ignore_errors: yes
  failed_when: false
  become: yes

- name: Set root password and allow root login with password (only if no password)
  mysql_user:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: root
    password: "{{ mysql_root_password }}"
    host_all: yes
    check_implicit_admin: yes
  no_log: true
  when: mysql_root_access.failed
  become: yes

- name: Create WordPress Database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: yes

- name: Create WordPress User
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: '{{ wordpress_db_name }}.*:ALL'
    host: "localhost"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: yes

