---
- name: Install PHP and modules
  apt:
    name:
      - php
      - php-mysql
      - libapache2-mod-php
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
    state: present
    update_cache: yes

